#ifndef QSYSMLPLUGIN_GLOBAL_H
#define QSYSMLPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QSYSMLPLUGIN_LIBRARY)
#  define QSYSMLPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QSYSMLPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QSYSMLPLUGIN_GLOBAL_H
