#ifndef QLOGICCIRCUITSIM_GLOBAL_H
#define QLOGICCIRCUITSIM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QLOGICCIRCUITSIM_LIBRARY)
#  define QLOGICCIRCUITSIMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QLOGICCIRCUITSIMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QLOGICCIRCUITSIM_GLOBAL_H
